[package]
name = "expense-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.26", features = ["derive"] }
csv = "1.3.1"
num-traits = "0.2.19"
serde = { version = "1.0.217", features = ["derive"] }
